spring:
  cloud:
    gateway:
      routes:
        - id: member_route
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}
        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}
        - id: third_party_route
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/third-party/**
          filters:
            - RewritePath=/api/third-party/?(?<segment>.*), /$\{segment}
        - id: renren_fast_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
              - RewritePath=/api/?(?<segment>.*), /renren-fast/$\{segment}