server:
  port: 30000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.130:8848
    alicloud:
      access-key: LTAI5tDhpGaCNunDsvNm5YcJ
      secret-key: 0xhPfLoVqNRgTHtJq0BE8LlaBdJqD3
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com