server:
  port: 30000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.130:8848
    alicloud:
      access-key: LTAI5tQ9kPoE97vhCFtbXNDJ
      secret-key: gKZrZoR1rxmb0fVuNgfPYym8Qeh2Q8
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
